<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Harvest Lane Gardens</title>
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/harvest_gardens.css" media="screen">
    <link rel="stylesheet" type="text/css" href="css/js.css" media="screen">
    <link rel="stylesheet" type="text/css" href="css/login.css" media="screen">
  </head>

  <body>
    <header id="header">
        <h1><i class="fa fa-leaf"></i>  Harvest Lane Gardens</h1>
    </header>

    {% block content %}{% endblock %}

    <footer>
      <div class="bottom-border">
        <p class="copyright">Harvest Lane Gardens</p>
      </div>
    </footer>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="/js/harvest_gardens.js"></script>
  </body>
</html>

