
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Homepage - Harvest Lane Gardens</title>
    
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/semantic.min.css">
  <link rel="stylesheet" type="text/css" href="/css/login.css" media="screen">
  <script src="/js/login.js"></script>
</head>
<body>

<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <div class="content">
        Inventory Administrative Log-in
      </div>
    </h2>

    <form class="ui large form" method="POST" >
      <div class="ui stacked segment">
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            <input type="text" name="email" placeholder="E-mail address">
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <input type="password" name="password" placeholder="Password">
          </div>
        </div>
        <button type="submit" class="ui fluid large teal submit button">Login</button>
      </div>




      <div class="ui error message"></div>

    </form>

  </div>
</div>


      <div class="ui inverted vertical footer segment">
        <div class="ui container">
          <div class="ui stackable inverted divided equal height stackable grid">
            <div class="three wide column">
              <h4 class="ui inverted header">About Us</h4>
              <div class="ui inverted link list">
                <a href="#" class="item">Contact Us</a>
                <a href="#weBelieve" class="item">What We Believe</a>
              </div>
            </div>
            <div class="seven wide column">
              <h4 class="ui inverted header">HLG Friends</h4>
              <a href="http://www.jlgardens.net">Joy & Laughter Gardrens</a>
            </div>
          </div>
        </div>
      </div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="/semantic.min.js"></script>
  <script src="/js/harvest_gardens.js"></script>
</body>

</html>

